import "~/styles/globals.css";
import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Inter } from "next/font/google";
import { Toaster } from "sonner";

import { TRPCReactProvider } from "~/trpc/react";
import { cn } from "~/lib/utils";
import { ThemeProvider } from "~/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Code-Pulse",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html
			className={cn(geist.variable, "font-sans", inter.variable)}
			lang="en"
			suppressHydrationWarning
		>
			<body suppressHydrationWarning>
				<TRPCReactProvider>
					<ThemeProvider>
						<Suspense
							fallback={
								<div className="min-h-screen bg-background flex items-center justify-center">
									<div className="flex flex-col items-center gap-3">
										<div className="w-8 h-8 rounded-full border-2 border-primary border-t-transparent animate-spin" />
										<p className="text-muted-foreground text-sm">Loading…</p>
									</div>
								</div>
							}
						>
							{children}
						</Suspense>
						<Toaster richColors position="top-right" />
					</ThemeProvider>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
