import "~/styles/globals.css";
import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import { Suspense } from "react";
import { Toaster } from "sonner";
import { LoadingScreen } from "~/components/LoadingScreen";
import { ThemeProvider } from "~/components/ThemeProvider";
import { cn } from "~/lib/utils";
import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Code-Pulse",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html
			className={cn(geist.variable, "font-sans", inter.variable)}
			lang="en"
			suppressHydrationWarning
		>
			<body suppressHydrationWarning>
				<TRPCReactProvider>
					<ThemeProvider>
						<Suspense fallback={<LoadingScreen label="Loading…" />}>
							{children}
						</Suspense>
						<Toaster position="top-right" richColors />
					</ThemeProvider>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
